#!/usr/bin/env bash
# Setup haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server web-01 52.70.84.210:80 check
        server web-02 52.202.28.73:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
